server:
  http_listen_address: 0.0.0.0
  http_listen_port: 5050
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  
metrics:
  wal_directory: C:\Program Files\Grafana Agent\grafana_wal
  global:
    scrape_interval: 1m
 
logs:
  configs:
  - name: default
    positions:
      filename: C:\Program Files\Grafana Agent\positions.yaml
    scrape_configs:
    - job_name: iis
      static_configs:
       - targets: [test]
         labels:
           Env: IOPERF-test
           host: test
           servergroup: IOPERF
           job: iis
           __path__: C:\inetpub\logs\LogFiles\W3SVC1\u_*.log       
    clients:
      - url: http://10.195.0.219:3100/loki/api/v1/push  
        batchwait: 1s
        batchsize: 102400
        external_labels: 
          env : IO-PERF      
    
integrations:    
  windows_exporter:
    enabled: true
    wal_truncate_frequency: "60m"
    enabled_collectors: 'cpu,cs,logical_disk,net,os,service,system,process,tcp,thermalzone'
    


